// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjfnxv38NlcJkIC0dmVTQN41qcTBpzGi0',
    appId: '1:898448789966:web:75b4e3b76b3813d9c01b9f',
    messagingSenderId: '898448789966',
    projectId: 'acqa-39253',
    authDomain: 'acqa-39253.firebaseapp.com',
    storageBucket: 'acqa-39253.firebasestorage.app',
    measurementId: 'G-R3LZDQVJDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIO1yTI0EeIn8w7c4Ex3X59Anx_Pll62Y',
    appId: '1:898448789966:android:420c9e8ed0a5213fc01b9f',
    messagingSenderId: '898448789966',
    projectId: 'acqa-39253',
    storageBucket: 'acqa-39253.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-hGeHOSS59MHNY0krgrHhni-yCGK9wVI',
    appId: '1:898448789966:ios:1da8685ec94e37c0c01b9f',
    messagingSenderId: '898448789966',
    projectId: 'acqa-39253',
    storageBucket: 'acqa-39253.firebasestorage.app',
    iosBundleId: 'com.example.acqa',
  );

}